### ISSUE TITLE
Speed up training

### ISSUE THREAD

**Issue by trickovicmatija** [devCellPy-Team/devCellPy#1]
Hello,
Thanks for the nice tool! I have some problems training the model with reference data:
I have downloaded a big reference (~15GB is the "--trainNormExpr" file). On the other hand, it has only 2 layers - cell types and cell sub-types (without the timepoint info). It is taking a really long time (it timed-out on my HPC after 36h), and takes a lot of RAM (~200GB, not a problem for now). I want to speed up the process.

Is it possible to run cross-validation but somehow skip the timepoint prediction (I am not sure I got that right, I am guessing based on the info in the Tutorial)? Would that affect the performance of the model at the end? 

Also, I have the idea to split the count_table (together with metadata) based on cell type and run those trainings (and after predictions) separately, and afterwards concat all the predictions. Does it sound as a good idea?

Thank you very much,
Matija

**Comment by duocang** [comment]
Hi Matija,

would it be possible for you to share the workflow that you generate trianing data from Zheng etal. PBMC data?

There are so many data of the paper and I am not sure which one I should pick and how to creat a seurat object with mate info of `c("Celltype1", "Celltype2", "Timepoint", "Celltype3")`.
[data like:  Single Cell 3 ' Paper : Zheng et al . 2017 ( v1 Chemistry )](https://www.10xgenomics.com/resources/datasets?query=&page=1&configure%5Bfacets%5D%5B0%5D=chemistryVersionAndThroughput&configure%5Bfacets%5D%5B1%5D=pipeline.version&configure%5BhitsPerPage%5D=500)


Best 
Juyi

**Comment by trickovicmatija** [comment]
Hello Juyi,
Thanks for the reply. I wasn't using that reference, but "A single-cell atlas of human and mouse white adipose tissue", Emont et al. 2022, Nature.
I managed to solve the problem (it is still running so I am not 100% sure). The thing is that there is no cli-flag to set the number of threads. I assumed that this is because it can be run only on single thread. Nevertheless, I have tried to set more threads on my HPC and managed to get the speed-up. So, I guess the script will use all available threads on the machine, without the way to set that.
Maybe it is not a bad idea to explicitly say that in the Tutorial, just for future users.

Thanks again,
Matija

**Comment by fxgaldos** [comment]
Hi Matija,

Apologies for the delayed reply. The timepoint layer is not necessary for running devCellPy. Would you mind sharing with us your label info file (csv containing the layout of your layers) with the annotation hierarchy? If there is an error here, it may be causing issues with the training. 

The algorithm will use the maximum number of threads available, we will add this to the documentation.

Of note, one reason we are seeing longer training times for larger datasets is due to current devcellpy version undergoing automated hyper parameter tuning per layer which we have seen increase prediction accuracies. We are in the process of implementing an option where users can use preset values of tuned parameters which will increase speed of training.

**Comment by trickovicmatija** [comment]
Hello, 

Thanks for the reply. At the end, I have managed to run the tool and predict labels in query dataset. Still, I think there is a bug that I have handled manually:
In the function "reorder_pickle" you are checking if the input file ends with csv using an undefined variable "train_normexpr" https://github.com/devCellPy-Team/devCellPy/blob/48304762b1148dc742a63e41c51c1c9b02587dd7/devcellpy_full_code.py#L391, which is making the predict command to crash. I have changed that variable to "path" (as in input arguments) locally, and it worked!

Best regards,
Matija

**Comment by sidrayx** [comment]
Hi Matija,

Thank you so much for bringing this to our attention. We have updated our documentation and code, and there is also an option '--stdParams' now to skip hyper parameter fine tuning entirely and use the optimal parameters from our developmental cardiac dataset.

Best,
Sidra

**Comment by pinunQ** [comment]
> Hello,
> 
> Thanks for the reply. At the end, I have managed to run the tool and predict labels in query dataset. Still, I think there is a bug that I have handled manually: In the function "reorder_pickle" you are checking if the input file ends with csv using an undefined variable "train_normexpr"
> 
> https://github.com/devCellPy-Team/devCellPy/blob/48304762b1148dc742a63e41c51c1c9b02587dd7/devcellpy_full_code.py#L391
> 
> , which is making the predict command to crash. I have changed that variable to "path" (as in input arguments) locally, and it worked!
> Best regards, Matija

Hello I have tried to use the same and was able to train the model but when i tried to perform the prediction I started to get this error.

https://github.com/devCellPy-Team/devCellPy/issues/2#issue-1437717618

Did you face the same error?
