### ISSUE TITLE
Label info File 

### ISSUE THREAD

**Issue by pinunQ** [devCellPy-Team/devCellPy#2]
Hi, I have a question during training the model for analysis.

I was able to solve the label file problem however the prediction has made me face this problem.

CLI-
`nohup ~/devcellpy --runMode predictAll \`
    `--predNormExpr ~/merge_met/X.csv \`
    `--layerObjectPaths ~/devcellpy_training_20221107170844/Root/Root_object.pkl \`
    `--rejectionCutoff 0.5 &> devpred.log &`

I do not know how to get that label.csv file.

The following error I am receiving

`[<Layer: 'Root', Level: 0, labeldict: {0: 'Cardiomyocytes', 1: 'Fibroblast', 2: 'Epicardial cells', 3: 'Endothelial cells', 4: 'Immune cells',` `5: 'Erythroid', 6: 'Smooth Muscle cells', 7: 'Neurons'}, Trained: True>]`
`Traceback (most recent call last):`
`File "~/devcellpy", line 8, in <module> sys.exit(main())`
`File "~/devcellpy/devcellpy.py", line 1204, in` `main predictionAll(pred_normexpr, layer_paths)`
`  File "~/devcellpy/devcellpy.py", line 145, in` `training parameters = layer.finetune(50, 30, train_normexpr, train_metadata)`
`File "~/devcellpy/devcellpy.py", line 317, in` `predictionAll reorder_pickle(val_normexpr, featurenames)`
`File "~/devcellpy/devcellpy.py", line 395, in` `reorder_pickle norm_express.set_index('gene', inplace=True)`
`File "~/python3.10/site-packages/pandas/util/_decorators.py", line 311, in` `wrapper return func(*args, **kwargs)`
`File "~/python3.10/site-packages/pandas/core/frame.py", line 5494, in` `set_index`
`KeyError: "None of ['gene'] are in the columns"`

**Comment by fxgaldos** [comment]
Hi PinunQ,

Apologies for delay in responding. This error may be related to the formatting of the input to "--predNormExpr". Would you mind sharing the first 5 lines of this file?

**Comment by fxgaldos** [comment]
Closing given inactivity. Please feel free to reopen!
