### ISSUE TITLE
How to install to use devCellPy as a command

### ISSUE THREAD

**Issue by goepp** [devCellPy-Team/devCellPy#5]
I do not manage to install devCellPy as a terminal command:

## Problem description
The toturials suggest that devCellPy should be run as a terminal command:
```
devCellPy 
    --runMode predictOne 
    --predNormExpr "/path/to/lietal2019_norm_express.csv"
    --predMetadata "/path/to/lietal2019_metadata.csv"
    --layerObjectPaths "/Cardiac_Atlas_Trained_Model/Root_object.pkl"
    --rejectionCutoff 0.5
```

However, the [installation guide in the README](https://github.com/devCellPy-Team/devCellPy/blob/fdc67ee5b30d4e911c1629f2ee416fa5613358f1/README.md?plain=1#L50) suggests running devCellPy from the python command:
```
python3 /path/to/devcellpy ***commands***
```

## What I manage to do
I manage to install devCellPy as a python package, using:
```
conda create -n devcellpy python=3.9
conda activate devcellpy
git clone https://github.com/devCellPy-Team/devCellPy
cd devCellPy
pip install .
```
After which the installation completes sucessfully and I can import the package in python using `import devCellPy`.

## Conclusion
Could you specify the steps to install the python package as a command line tool?

**Comment by sidrayx** [comment]
Hello,

Thank you for your interest in devCellPy! After you've installed the package and all the dependencies, you should be able to run the package directly in the command line using the terminal command "devCellPy ...". Apologies for the confusion, and we will update the README with the correct instructions.

Best,
SIdra

**Comment by goepp** [comment]
Thank you for your answer!

I ran it again and it worked:
```
git clone https://github.com/devCellPy-Team/devCellPy
cd devCellPy

conda create -n devcellpy_env --file requirements.txt
conda activate devcellpy_env
pip install -e .
which devcellpy
```
And the last line does output the devcellpy executable.
Sorry for the inconvenience.
