### ISSUE TITLE
How to save the output of the train data

### ISSUE THREAD

**Issue by eridona** [devCellPy-Team/devCellPy#6]
Hello,
I am wondering if there is a way to specify where to save the ouput of the training.
Thanks,
Erika

**Comment by sidrayx** [comment]
Hi Erika,

Thank you for your interest in devCellPy! All outputs of the training should be automatically saved to your working directory already. A folder with the name "devcellpy_training_[date]" will be made and contains all the models and training statistics.

Best,
Sidra
